sudo: required

services:
  - docker

language: go

go:
  - 1.8

before_script:
  - mkdir -p $HOME/gopath/src/k8s.io
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/autoscaler
  - hack/install-verify-tools.sh
  - export PATH=$GOPATH/bin:$PATH

install: true

jobs:
  include:
    - stage: Install
      script: hack/for-go-proj.sh install
    - stage: Verify
      script: hack/verify-all.sh -v
    - stage: Test
      script: hack/for-go-proj.sh test
