apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterproportionalscalers.autoscaling.k8s.io
spec:
  group: autoscaling.k8s.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: clusterproportionalscalers
    singular: clusterproportionalscaler
    kind: ClusterProportionalScaler
    shortNames:
    - cps
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          required:
            - selector
          properties:
            selector:
              type: object
            updatePolicy:
              properties:
                updateMode:
                  type: string
            resourcePolicy:
              properties:
                containerPolicies:
                  type: array
